# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        files: '^(python|R)/'
      - id: end-of-file-fixer
        files: '^(python|R)/'
      - id: check-yaml
        files: '^(python|R)/'
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
      - id: black
        files: '^python/'
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.0
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [ --fix ]
        files: '^python/'
      # Run the formatter.
      - id: ruff-format
        files: '^python/'
