# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
        files: '^(python|R)/'
      - id: check-yaml
        files: '^(python|R)/'
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.0
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [ --fix ]
        files: '^python/'
      # Run the formatter.
      - id: ruff-format
        files: '^python/'
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: [ '--baseline', '.secrets.baseline' ]
  - repo: local
    hooks:
      - id: copy-resources
        name: "Copy Package Resources"
        entry: ./scripts/copy_resources.sh
        language: script
        pass_filenames: false
      - id: generate-md-docs
        name: "Generate Zensical Markdown files"
        entry: python3 ./scripts/generate_docs.py
        args: ["--output-dir", "docs/generated", "--template-dir", "docs/templates", "--rd-dir", "R/man"]
        language: system
        pass_filenames: false
