---
title: "CIDA SAS Macros"
date: "Last updated: `r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{CIDA SAS Macros}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = FALSE
)
```


## List of SAS macros

SAS macros in CIDAtools can be searched below, and their source code is available [here](https://github.com/CIDA-CSPH/CIDAtools/tree/master/inst/sas). 

```{r, eval=rmarkdown::pandoc_available("1.12.3")}
path <- system.file("sas", package = "CIDAtools")

  if(length(path)) {
    sas_files <- list.files(path, full.names = T)
  
    keywords <- sapply(sas_files, function(f) {
      lines <- readLines(f)
      keys <- lines[grepl("Keywords", lines, ignore.case = T)]
      gsub("\\*|\\* |Keywords: |;", "", keys, ignore.case = T)
    })
    
    sas_index <- data.frame(
      name = list.files(path, full.names = F), 
      keywords = keywords, row.names = NULL
    )
    
    DT::datatable(sas_index)
}
```
