[project]
name = "cidatools"
dynamic = ["version"]
description = "CIDAtools implementation for Python"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "jinja2>=3.1.6",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.2",
    "requests>=2.34.2",
]

[dependency-groups]
dev = [
    "coverage>=7.15.2",
    "detect-secrets>=1.5.0",
    "jupyterlab>=4.6.2",
    "pre-commit>=4.6.1",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "pytest-mock>=3.15.1",
]

[project.scripts]
cidatools = "cidatools.cli:cli"

[build-system]
requires = ["setuptools>=83.0", "setuptools_scm>=10.2.1"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
root=".."
write_to = "src/cidatools/version.py"

[tool.setuptools.package-data]
"cidatools" = ["resources/**/*"]

[tool.ruff]
line-length = 120
