[project]
name = "cidatools"
version = "2.0.0"
description = "CIDAtools implementation for Python"
readme = "README.md"
requires-python = ">=3.14"

dependencies = [
    "jinja2>=3.1.6",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.2",
]

[dependency-groups]
dev = [
    "coverage>=7.15.2",
    "detect-secrets>=1.5.0",
    "pre-commit>=4.6.1",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "pytest-mock>=3.15.1",
]

[project.scripts]
cidatools = "cidatools.cli:cli"

[tool.ruff]
line-length = 120
