# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  push:
    branches: [ "cleanup_edits_SM" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        r-version: ['release']
        os: [ubuntu-latest] #[ubuntu-latest, windows-latest, macos-latest]


    steps:
      - uses: actions/checkout@v4

      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
          use-public-rspm: true

      - name: Cache R
        uses: actions/cache@v4
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.r-version }}-${{ hashFiles('DESCRIPTION') }}-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-r-${{ matrix.r-version }}-${{ hashFiles('**/renv.lock') }}
            ${{ runner.os }}-r-${{ matrix.r-version }}



      - name: Install dependencies
        if: steps.cache-r.outputs.cache-hit != 'true'
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck,altdoc,quarto,roxygen2
          needs: check

      - name: Check Package
        uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
          error-on: '"error"'

      - name: Show testthat output
        if: always()
        run: |
          ## --------------------------------------------------------------------
          find '${{ runner.temp }}/package' -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-test-failures
          path: ${{ runner.temp }}/package
      - name: Document
        run: Rscript -e 'roxygen2::roxygenise()'

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 'latest' # Or a specific Quarto version like '1.4.0'

      - name: Install TinyTeX
        run: quarto install tinytex

      - name: Build Quarto Website
        run: Rscript -e 'altdoc::render_docs(path = ".", verbose = TRUE, parallel = FALSE, freeze = FALSE)'


